server:
  port: 8081

spring:
  application:
    name: translation-server

logging:
  level:
    com.example.foreverrip: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"